---
dockitems_remove_all: false
dockitems_remove:
  - Mail
  - Safari
  - Siri
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - Music
  - TV
  - App Store
  - System Preferences
  - Calendar
  - Terminal
  - Podcasts
  - Keynote
  - Pages
  - Numbers
  - "System Settings"

dockitems_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Commander One
    path: "/Applications/SetApp/Commander One.app"
    pos: 2
  - name: Thunderbird
    path: "/Applications/Thunderbird.app"
    pos: 3
  - name: BusyCal
    path: "/Applications/SetApp/BusyCal.app"
    pos: 4
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 5
  - name: Mona
    path: "/Applications/Mona.app"
    pos: 6
  - name: GoLand
    path: "/Users/ringods/Applications/GoLand.app"
    pos: 7
  - name: PyCharm
    path: "/Users/ringods/Applications/PyCharm.app"
    pos: 8
  - name: RustRover
    path: "/Users/ringods/Applications/RustRover.app"
    pos: 9
  - name: WebStorm
    path: "/Users/ringods/Applications/WebStorm.app"
    pos: 10
  - name: SQLPro Studio
    path: "/Applications/SetApp/SQLPro Studio.app"
    pos: 11
